# docker-compose.yml
# .env  <- EKL_TAG=7.8.0
# docker-compose --compatibility up -d
version: "3.1"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${EKL_TAG}
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
    deploy:
      resources:
        limits:
          memory: 512M
  kibana:
    image: docker.elastic.co/kibana/kibana:${EKL_TAG}
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    deploy:
      resources:
        limits:
          memory: 512M
  logstash:
    image: docker.elastic.co/logstash/logstash:${EKL_TAG}
    depends_on:
      - elasticsearch
    ports:
      - "9600:9600"
    deploy:
      resources:
        limits:
          memory: 512M
    stdin_open: true
    tty: true
    entrypoint: logstash -e 'input { stdin{} }  output { elasticsearch {  hosts => ["elasticsearch:9200"] } }'

networks:
  default:
    external:
      name: elk #使用外部网络，要提前创建 docker network create elk --driver bridge
